version: '3'

services:
  web:
    image: tonywell/angulardev
    stdin_open: true
    tty: true
    privileged: true
    user: node
    environment:
      TZ: Asia/Shanghai
    working_dir: /home/node/workspace
    volumes:
      - ./:/home/node/workspace
    ports:
      - "8081:8081"
      - "6555:22"
    entrypoint: ["zsh"]
